module.exports = {
    acc: 'settings',
    access: 'settings',
    browse: 'browsehierarchy/',
    coll: 'collection/',
    collection: 'collection/',
    collections: 'collection/',
    group: 'usermanagement/local/group/',
    groups: 'usermanagement/local/group/',
    hier: 'browsehierarchy/',
    hierarchy: 'browsehierarchy/',
    item: 'item/',
    launch: 'launcher',
    launcher: 'launcher',
    open: 'launcher',
    role: 'usermanagement/local/role/',
    roles: 'usermanagement/local/role/',
    s: 'search/',
    search: 'search/',
    set: 'settings',
    settings: 'settings',
    tax: 'taxonomy/',
    taxo: 'taxonomy/',
    taxonomy: 'taxonomy/',
    user: 'usermanagement/local/user/',
    users: 'usermanagement/local/user/',
}
