module.exports = {
    browse: 'browsehierarchy/',
    coll: 'collection/',
    collection: 'collection/',
    collections: 'collection/',
    group: 'usermanagement/local/group/',
    groups: 'usermanagement/local/group/',
    hier: 'browsehierarchy/',
    hierarchy: 'browsehierarchy/',
    role: 'usermanagement/local/role/',
    roles: 'usermanagement/local/role/',
    tax: 'taxonomy/',
    taxo: 'taxonomy/',
    taxonomy: 'taxonomy/',
    user: 'usermanagement/local/user/',
    users: 'usermanagement/local/user/',
}
