name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.js'
      - package.json
      - pnpm-lock.yaml
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.js'
      - package.json
      - pnpm-lock.yaml

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # must come before setup-node
      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v6.3.0
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: npx eslint .
