name: GitHub Release & NPM Publish

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Run Tests 🧪
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          run_install: false
          version: latest
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install
      # Ensure `eq` is on PATH with a fake .equellarc, some tests shell out to it
      - run: pnpm link
      - run: |
          echo '{"root": "http://localhost", "token": "fake"}' > .equellarc
      - run: pnpm test

  github-release:
    needs: test
    name: Create GitHub Release 🚀
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --generate-notes

  npm-publish:
    needs: test
    name: Publish to NPM 📦
    permissions:
      contents: read
      id-token: write # for OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # Sets up .npmrc file to publish to npm
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      # Setup pnpm
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          run_install: true
          version: latest
      # Need no git checks or this fails with ERR_PNPM_GIT_UNKNOWN_BRANCH
      # because we checked out a tag which is a detached head
      # Using Trusted Publishers, no NPM token https://docs.npmjs.com/trusted-publishers
      - run: pnpm publish --access public --no-git-checks
