name: Unit Tests

on:
    pull_request:
    workflow_call:

jobs:
  test:
    name: Run Tests 🧪
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          run_install: false
          version: latest
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install
      # Ensure `eq` is on PATH with a fake .equellarc, some tests shell out to it
      - run: pnpm link
      - run: |
          echo '{"root": "http://localhost", "token": "fake"}' > .equellarc
      - run: pnpm test
